package com.healthpay.model;

public enum ErrorType {
    DUPLICATE_CLAIM,
    INVALID_AMOUNT,
    MISSING_INFORMATION,
    PROVIDER_NOT_AUTHORIZED,
    PATIENT_NOT_ELIGIBLE,
    SERVICE_NOT_COVERED,
    CODING_ERROR,
    BILLING_DISCREPANCY
}
